# Generated by Django 5.2 on 2025-04-24 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_colorvariant_quantityvariant_sizevariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.colorvariant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.quantityvariant",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.sizevariant",
            ),
        ),
    ]
